#ifndef TOKEN_HPP
#define TOKEN_HPP

enum TokenType {
    IDENTIFIER,
    INT_LITERAL, FLOAT_LITERAL, STRING, _NULL,

    PLUS, MINUS, STAR, SLASH, PERCENT,
    AND, OR, ASSIGN_EQ, EQUALITY_EQ, 
    MORE, LESS, MORE_EQ, LESS_EQ, DOT,
    AMPERSAND,

    SET, IF, FOR, WHILE, CONTINUE, BREAK, FN
};

#endif